# Generated by Django 5.0.6 on 2024-06-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='StudentClass',
            new_name='Studentclass',
        ),
    ]
