# Generated by Django 5.0.6 on 2024-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=20)),
                ('courses_code', models.SmallIntegerField()),
                ('courses_instuctor', models.CharField(max_length=20)),
                ('courses_assignment', models.CharField(max_length=20)),
                ('courses_level', models.CharField(max_length=20)),
                ('courses_department', models.CharField(max_length=20)),
                ('courses_syllabus', models.CharField(max_length=20)),
                ('courses_exams', models.CharField(max_length=20)),
                ('courses_duration', models.SmallIntegerField()),
            ],
        ),
    ]
