# Generated by Django 5.0.6 on 2024-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.IntegerField()),
                ('class_capacity', models.IntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('class_lecture', models.CharField(max_length=20)),
                ('class_id', models.IntegerField()),
                ('class_rep', models.CharField(max_length=20)),
                ('class_description', models.TextField()),
                ('class_attendance', models.IntegerField()),
                ('class_activity', models.CharField(max_length=20)),
            ],
        ),
    ]
